projtodo/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
	path('todolist/', include('ztodoapp.urls')),
    path('admin/', admin.site.urls),
]

ztodoapp/urls.py
from django.urls import path

from . import views


app_name = 'todo'
urlpatterns = [
	path('login/', views.loginUser, name='login'),
	path('logout/', views.logoutUser, name='logout'),
	path('home/', views.home, name='home'),
	path('register/', views.register, name='register'),
	path('deleteTask/<int:id>/', views.deleteTask, name='deleteTask'),
	path('completeTask/<int:id>/', views.completeTask, name='completeTask'),
	path('editTask/<int:id>/', views.editTask, name='editTask'),
]

ztodoapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Todo(models.Model):
	task = models.CharField(max_length=25)
	user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
	task_status = models.BooleanField()


	def __repr__(self):
		return '<Todo {} {} {}'.format(
			self.task, 
			self.user,
			self.task_status
			)

ztodoapp/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='username', max_length=150)
	password = forms.CharField(label='password', max_length=128)

class RegisterForm(forms.Form):
	first_name = forms.CharField(label='first_name', max_length=50)
	last_name = forms.CharField(label='last_name', max_length=50)
	email = forms.CharField(label='email', max_length=100)
	password = forms.CharField(label='password', max_length=50)

class AddTaskForm(forms.Form):
	task = forms.CharField(label='task', max_length=25)

ztodoapp/views.py
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User
from .models import Todo
from .forms import RegisterForm, AddTaskForm, LoginForm


@login_required
def home(request):
	if request.method == 'POST':

		form = AddTaskForm(request.POST)

		if form.is_valid():
			task = Todo(
				task=request.POST['task'],
				user_id=request.user.id,
				task_status=False # pending todo
				)			
			task.save()
			return HttpResponseRedirect(reverse('todo:home'))
		else:
			messages.error(request, form.errors)

	tasks = Todo.objects.filter(user_id=request.user.id)

	form = AddTaskForm()
	return render(request, 'todo/home.html', {'tasks': tasks})

def loginUser(request):
	if request.method == 'POST':

		form = LoginForm(request.POST)

		if form.is_valid():

			username = request.POST['username']
			password = request.POST['password']

			user = authenticate(request, username=username, password=password)
			if user is not None:
				login(request, user)
				tasks = Todo.objects.filter(user_id=request.user.id)
				return render(request, 
					'todo/home.html', 
					{
						'user': request.user.username,
						'tasks': tasks,
					})
			else:
				messages.error(request, 'Authentication Failed')
		else:
			messages.error(request, form.errors)

	return render(request, 'todo/login.html')

def logoutUser(request):
	logout(request)
	return HttpResponseRedirect(reverse('todo:login'))

def register(request):
	if request.method == 'POST':

		form = RegisterForm(request.POST)

		print('email')
		print(request.POST.get('email'))
		print('object')
		print(User.objects.filter(username=request.POST.get('email')))

		if form.is_valid():
			if User.objects.filter(username=request.POST.get('email')).count() == 0:
				print('#'* 30)
				user = User.objects.create_user(
					first_name=request.POST['first_name'],
					last_name=request.POST['last_name'],
					email=request.POST['email'],
					username=request.POST['email'],
					password=request.POST['password'],
					date_joined=timezone.now(),
					is_superuser=False,
					is_staff=False,
					is_active=True
					)			
				user.save()
				return HttpResponseRedirect(reverse('todo:login'))
			else:
				messages.error(request, "username already exists.")
		else:
			messages.error(request, form.errors)

	form = RegisterForm()
	return render(request, 'todo/register.html')

def deleteTask(request, id):

	Todo.objects.filter(pk=id).delete()
	return HttpResponseRedirect(reverse('todo:home'))

def completeTask(request, id):
	t = Todo.objects.get(pk=id)

	if t.task_status == True:
		t.task_status = False
		t.save()
	else:
		t.task_status = True
		t.save()

	return HttpResponseRedirect(reverse('todo:home'))

def editTask(request, id):
	if request.method == 'POST':

		form = AddTaskForm(request.POST)

		if form.is_valid():
			t = Todo.objects.get(pk=id)
			t.task = request.POST['task']
			t.save()
			return HttpResponseRedirect(reverse('todo:home'))
		else:
			messages.error(request, form.errors)

	form = AddTaskForm()
	return render(request, 'todo/editForm.html')	

ztodoapp/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %} {% endblock %}
	</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link 
		rel="stylesheet" 
		type="text/css" 
		href="{% static 'todo/todo.css' %}"
	>
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="header-container">
				<div class='header'>A Todo List</div>
			</div>
		</div>
		<div class='error'>
			{% if messages %}
				{% for message in messages %}
					{{ message }}
				{% endfor %}
			{% endif %}	
		</div>		
			{% block body %} {% endblock %}
		
	</div>

	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static 'todo/todo.js' %}"></script>
</body>
</html>

ztodoapp/templates/todo/editForm.html
{% extends 'todo/base.html' %}

{% block title %}
	A Todo List - Edit
{% endblock %}

{% block body %}
	<div class="login-page-name">
		<span>Edit</span>
	</div>
<!-- 	<form action="{% url 'todo:login' %}" method='post'>
		{% csrf_token %}
		<label>Username</label>
		<input type="text" name="username">
		<label>Password</label>
		<input type="password" name="password">
		<button>Submit</button>
		<a href="{% url 'todo:register' %}">Register New User</a>
	</form> -->
	<div class="login-form-container">
		<form action="{% url 'todo:login' %}" method='post'>
			{% csrf_token %}
		  <div class="form-group">
		    <label for="username">Task</label>
		    <input type="email" class="form-control" id="username" aria-describedby="emailHelp" name="username" value={{}}>
		  </div>
		  <div class="form-group">
		    <label for="password">Password</label>
		    <input type="password" class="form-control" id="password" name="password">
		  </div>
		  <button type="submit" class="btn btn-primary">Submit</button> 
		  <a href="{% url 'todo:register' %}">Register New User</a>
		</form>
	</div>

{% endblock %}

ztodoapp/templates/todo/home.html
{% extends 'todo/base.html' %}

{% block title %}
	A Todo List - Home
{% endblock %}

{% block body %}


	<div class="add-task-bar">
		<div class='add-task-box'>
			<form action="{% url 'todo:home' %}" method='POST'>
				{% csrf_token %}
				<!-- <label>Add Task</label> -->
				<!-- <input type="text" name="task" placeholder="Type Here..." 
					class="add-task-box">
				<button>Add</button> -->

				<div class="input-group mb-3">
				  <input type="text" class="form-control" placeholder="Type here..." aria-label="task" name="task" aria-describedby="button-addon2" maxlength="25" required>
				  <div class="input-group-append">
				    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Add Task</button>
				  </div>
				</div>		
			</form>

		</div>
		<div class="user-info">
			<div>{{ user }}</div>
			<a href="{% url 'todo:logout' %}">Logout</a>
		</div>
	</div>	


	<div class="task-container">
		{% for task in tasks %}
			{% if task.task_status == 0 %}
				<div class="task-item">
					<div>{{ task.task|slice:":50" }}</div>
					<div>

						<a href="{% url 'todo:deleteTask' task.id %}" class="flat-button">
							<i class="fa fa-trash-o icon-size"></i>
						</a>

						<button class='flat-button edit-task' data-task="{{task.task}}" data-id="{{task.id}}">
							<i class="fa fa-edit icon-size"></i>
						</button>

						<a href="{% url 'todo:completeTask' task.id %}" class="flat-button">
							<i class="fa fa-check icon-size"></i>
						</a>

					</div>
				</div>
			{% else %}
				<div class="task-item-complete">
					<div>{{ task.task|slice:":50" }}</div>
					<div>

						<a href="{% url 'todo:deleteTask' task.id %}" class="flat-button">
							<i class="fa fa-trash-o icon-size"></i>
						</a>

						<button class='flat-button edit-task' data-task="{{task.task}}" data-id="{{task.id}}">
							<i class="fa fa-edit icon-size"></i>
						</button>

						<a href="{% url 'todo:completeTask' task.id %}" class="flat-button">
							<i class="fa fa-check icon-size complete"></i>
						</a>

					</div>
				</div>
			{% endif %}
		{% endfor %}
	</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Edit Task</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <form action="" method="POST" id="editForm">
      	{% csrf_token %}
	      <div class="modal-body update-task">
	        <input 
	        	class='update-task'
	        	type="text" 
	        	name="task" 
	        	id='edit-modal' 
	        	placeholder="Add task here..." 
	        	maxlength="25"
	        	required>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        <button type="submit" class="btn btn-primary">Save changes</button>
	      </div>
	    </form>

    </div>
  </div>
</div>
	
{% endblock %}

ztodoapp/templates/todo/login.html
{% extends 'todo/base.html' %}

{% block title %}
	A Todo List - Login
{% endblock %}

{% block body %}
	<div class="login-page-name">
		<span>Login</span>
	</div>
	<div class="login-form-container">
		<form action="{% url 'todo:login' %}" method='post'>
			{% csrf_token %}
		  <div class="form-group">
		    <label for="username">Email address</label>
		    <input type="email" class="form-control" id="username" aria-describedby="emailHelp" name="username" required>
		  </div>
		  <div class="form-group">
		    <label for="password">Password</label>
		    <input type="password" class="form-control" id="password" name="password" required>
		  </div>
		  <button type="submit" class="btn btn-primary">Login</button> 
		  <a href="{% url 'todo:register' %}">Register New User</a>
		</form>
	</div>

{% endblock %}

ztodoapp/templates/todo/register.html
{% extends 'todo/base.html' %}

{% block title %}
	A Todo List - Register
{% endblock %}

{% block body %}
		<div class="login-page-name">
			<span>Register New User</span>
		</div>
		<div class="login-form-container">
			<form action="{% url 'todo:register' %}" method="post">
				{% csrf_token %}
				<div class="form-group">
			    <label for="first_name">First Name</label>
			    <input type="text" class="form-control" id="first_name" aria-describedby="firstname" name="first_name" required
			    maxlength="50">
			  </div>
				<div class="form-group">
			    <label for="last_name">Last Name</label>
			    <input type="text" class="form-control" id="last_name" aria-describedby="lastname" name="last_name" required
			    maxlength="50">
			  </div>
				<div class="form-group">
			    <label for="email">Email Address</label>
			    <input type="email" class="form-control" id="email" aria-describedby="email" name="email" required
			    maxlength="100">
			  </div>
				<div class="form-group">
			    <label for="password">Password</label>
			    <input type="password" class="form-control" id="password" name="password" required
			    maxlength="50">
			  </div>
				<button>Submit</button>
			</form>
		</div>

{% endblock %}